# Generated by Django 5.2 on 2025-04-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=100)),
                ('foodDescription', models.TextField(max_length=100)),
                ('foodRating', models.IntegerField()),
                ('foodIngredients', models.CharField(max_length=200)),
                ('foodRecipe', models.CharField(max_length=500)),
                ('foodImage', models.ImageField(upload_to='food_images/')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=100)),
                ('foodDescription', models.TextField(max_length=100)),
                ('foodRating', models.IntegerField()),
                ('foodIngredients', models.CharField(max_length=200)),
                ('foodRecipe', models.CharField(max_length=500)),
                ('foodImage', models.ImageField(upload_to='food_images/')),
            ],
        ),
    ]
