# Generated by Django 5.2 on 2025-04-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcrud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperequest',
            name='approvalStatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
